//
//  ChipCommandValues.h
//  BluetoothRobotControlLibrary
//
//  Created by Forrest Chan on 02/11/15.
//  Copyright (c) 2015 WowWee Group Limited. All rights reserved.
//

#import <Foundation/Foundation.h>;

typedef NS_OPTIONS(uint8_t, kChipChargingStatus) {
    kChipNotCharging = 0x00,
    kChipCharging = 0x01,
    kChipChargingFinish = 0x02,
};

typedef NS_OPTIONS(uint8_t, kChipSoundFileValue) {
    kChipSoundFile_BARK_X1_ANGRY_A34=1,
    kChipSoundFile_BARK_X1_CURIOUS_PLAYFUL_HAPPY_A34=2,
    kChipSoundFile_BARK_X1_NEUTRAL_A34=3,
    kChipSoundFile_BARK_X1_SCARED_A34=4,
    kChipSoundFile_BARK_X2_ANGRY_A34=5,
    kChipSoundFile_BARK_X2_CURIOUS_PLAYFUL_HAPPY_A34=6,
    kChipSoundFile_BARK_X2_NEUTRAL_A34=7,
    kChipSoundFile_BARK_X2_SCARED_A34=8,
    kChipSoundFile_CRY_A34=9,
    kChipSoundFile_GROWL_A_A34=10,
    kChipSoundFile_GROWL_B_A34=11,
    kChipSoundFile_GROWL_C_A34=12,
    kChipSoundFile_HUH_LONG_A34=13,
    kChipSoundFile_HUH_SHORT_A34=14,
    kChipSoundFile_LICK_1_A34=15,
    kChipSoundFile_LICK_2_A34=16,
    kChipSoundFile_PANT_FAST_A34=17,
    kChipSoundFile_PANT_MEDIUM_A34=18,
    kChipSoundFile_PANT_SLOW_A34=19,
    kChipSoundFile_SNIFF_1_A34=20,
    kChipSoundFile_SNIFF_2_A34=21,
    kChipSoundFile_YAWN_A_A34=22,
    kChipSoundFile_YAWN_B_A34=23,
    kChipSoundFile_ONE_A34=24,
    kChipSoundFile_TWO_A34=25,
    kChipSoundFile_THREE_A34=26,
    kChipSoundFile_FOUR_A34=27,
    kChipSoundFile_FIVE_A34=28,
    kChipSoundFile_SIX_A34=29,
    kChipSoundFile_SEVEN_A34=30,
    kChipSoundFile_EIGHT_A34=31,
    kChipSoundFile_NIGHT_A34=32,
    kChipSoundFile_TEN_A34=33,
    kChipSoundFile_ZERO_A34=34,
    kChipSoundFile_CHIP_DOG_COUGH_2_A34=35,
    kChipSoundFile_CHIP_DOG_CRY_2_A34=36,
    kChipSoundFile_CHIP_DOG_CRY_3_A34=37,
    kChipSoundFile_CHIP_DOG_CRY_4_A34=38,
    kChipSoundFile_CHIP_DOG_CRY_5_A34=39,
    kChipSoundFile_CHIP_DOG_EMO_CURIOUS_1_A34=40,
    kChipSoundFile_CHIP_DOG_EMO_CURIOUS_2_A34=41,
    kChipSoundFile_CHIP_DOG_EMO_CURIOUS_3_A34=42,
    kChipSoundFile_CHIP_DOG_EMO_EXCITED_1_A34=43,
    kChipSoundFile_CHIP_DOG_EMO_EXCITED_2_A34=44,
    kChipSoundFile_CHIP_DOG_EMO_EXCITED_3_A34=45,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_1_A34=46,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_2_A34=47,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_3_A34=48,
    kChipSoundFile_CHIP_DOG_EMO_RESPONSE_1_A34=49,
    kChipSoundFile_CHIP_DOG_EMO_RESPONSE_2_A34=50,
    kChipSoundFile_CHIP_DOG_EMO_RESPONSE_3_A34=51,
    kChipSoundFile_CHIP_DOG_EMO_SCARED_YIP_2_A34=52,
    kChipSoundFile_CHIP_DOG_EMO_SCARED_YIP_3_A34=53,
    kChipSoundFile_CHIP_DOG_FART_1_A34=54,
    kChipSoundFile_CHIP_DOG_FART_2_A34=55,
    kChipSoundFile_CHIP_DOG_FART_3_A34=56,
    kChipSoundFile_CHIP_DOG_GROWL_1_A34=57,
    kChipSoundFile_CHIP_DOG_GROWL_2_A34=58,
    kChipSoundFile_CHIP_DOG_GROWL_4_A34=59,
    kChipSoundFile_CHIP_DOG_GROWL_5_A34=60,
    kChipSoundFile_CHIP_DOG_HICCUP_1_A34=61,
    kChipSoundFile_CHIP_DOG_HICCUP_2_A34=62,
    kChipSoundFile_CHIP_DOG_HOWL_1_A34=63,
    kChipSoundFile_CHIP_DOG_HOWL_2_A34=64,
    kChipSoundFile_CHIP_DOG_HOWL_3_A34=65,
    kChipSoundFile_CHIP_DOG_HOWL_4_A34=66,
    kChipSoundFile_CHIP_DOG_HOWL_5_A34=67,
    kChipSoundFile_CHIP_DOG_LICK_2_A34=68,
    kChipSoundFile_CHIP_DOG_LICK_3_A34=69,
    kChipSoundFile_CHIP_DOG_LOWBATTERY_1_A34 =70,
    kChipSoundFile_CHIP_DOG_LOWBATTERY_2_A34 =71,
    kChipSoundFile_CHIP_DOG_MUFFLE_1_A34=72,
    kChipSoundFile_CHIP_DOG_MUFFLE_2_A34=73,
    kChipSoundFile_CHIP_DOG_MUFFLE_3_A34=74,
    kChipSoundFile_CHIP_DOG_PANT_1_A34=75,
    kChipSoundFile_CHIP_DOG_PANT_2_A34=76,
    kChipSoundFile_CHIP_DOG_PANT_3_A34=77,
    kChipSoundFile_CHIP_DOG_PANT_4_A34=78,
    kChipSoundFile_CHIP_DOG_PANT_5_L_A34=79,
    kChipSoundFile_CHIP_DOG_SMOOCH_1_A34=80,
    kChipSoundFile_CHIP_DOG_SMOOCH_2_A34=81,
    kChipSoundFile_CHIP_DOG_SMOOCH_3_A34=82,
    kChipSoundFile_CHIP_DOG_SNEEZE_1_A34=83,
    kChipSoundFile_CHIP_DOG_SNEEZE_2_A34=84,
    kChipSoundFile_CHIP_DOG_SNEEZE_3_A34=85,
    kChipSoundFile_CHIP_DOG_SNIFF_1_A34=86,
    kChipSoundFile_CHIP_DOG_SNIFF_2_A34=87,
    kChipSoundFile_CHIP_DOG_SNIFF_4_A34=88,
    kChipSoundFile_CHIP_DOG_SNORE_1_A34=89,
    kChipSoundFile_CHIP_DOG_SNORE_2_A34=90,
    kChipSoundFile_CHIP_DOG_SPECIAL_1_A34=91,
    kChipSoundFile_CHIP_SING_DO1_SHORT_A34=92,
    kChipSoundFile_CHIP_SING_DO2_SHORT_A34=93,
    kChipSoundFile_CHIP_SING_FA_SHORT_A34=94,
    kChipSoundFile_CHIP_SING_LA_SHORT_A34=95,
    kChipSoundFile_CHIP_SING_MI_SHORT_A34=96,
    kChipSoundFile_CHIP_SING_RE_SHORT_A34=97,
    kChipSoundFile_CHIP_SING_SO_SHORT_A34=98,
    kChipSoundFile_CHIP_SING_TI_SHORT_A34=99,
    kChipSoundFile_CHIP_DOG_BARK_3_A34=100,
    kChipSoundFile_CHIP_DOG_BARK_4_A34=101,
    kChipSoundFile_CHIP_DOG_BARK_5_A34=102,
    kChipSoundFile_CHIP_DOG_BARK_MULTI_3_A34 =103,
    kChipSoundFile_CHIP_DOG_BARK_MULTI_4_A34 =104,
    kChipSoundFile_CHIP_DOG_BARK_MULTI_5_A34 =105,
    kChipSoundFile_CHIP_DOG_BURP_1_A34=106,
    kChipSoundFile_CHIP_DOG_BURP_2_A34=107,
    kChipSoundFile_CHIP_DOG_COUGH_1_A34=108,
    kChipSoundFile_CHIO_DOG_EMO_RESPONSE_3A=109,
    kChipSoundFile_CHIP_DEMO_MUSIC_2=110,
    kChipSoundFile_CHIP_DEMO_MUSIC_3=111,
    kChipSoundFile_CHIP_DOG_BARK_1	=112,
    kChipSoundFile_CHIP_DOG_BARK_2	=113,
    kChipSoundFile_CHIP_DOG_BARK_MULTI_1=114,
    kChipSoundFile_CHIP_DOG_BARK_MULTI_2=115,
    kChipSoundFile_CHIP_DOG_CRY_1=116,
    kChipSoundFile_CHIP_DOG_EMO_CURIOUS_2A=117,
    kChipSoundFile_CHIP_DOG_EMO_EXCITED_3A=118,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_1A=119,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_2A=120,
    kChipSoundFile_CHIP_DOG_EMO_LAZY_3A=121,
    kChipSoundFile_CHIP_DOG_GROWL_3=122,
    kChipSoundFile_CHIP_DOG_HOWL_1A=123,
    kChipSoundFile_CHIP_DOG_HOWL_3A=124,
    kChipSoundFile_CHIP_DOG_HOWL_4A=125,
    kChipSoundFile_CHIP_DOG_HOWL_5A=126,
    kChipSoundFile_CHIP_DOG_LICK_1	=127,
    kChipSoundFile_CHIP_DOG_LOWBATTERY_1A=128,
    kChipSoundFile_CHIP_DOG_LOWBATTERY_2A=129,
    kChipSoundFile_CHIP_DOG_MUFFLE_1A=130,
    kChipSoundFile_CHIP_DOG_SMOOCH_3A=131,
    kChipSoundFile_CHIP_DOG_SNEEZE_1A=132,
    kChipSoundFile_CHIP_DOG_SNIFF_3=133,
    kChipSoundFile_CHIP_DOG_SNIFF_4A=134,
    kChipSoundFile_CHIP_MUSIC_DEMO_1=135,
    kChipSoundFile_CHIO_DOG_EMO_RESPONSE_1A=136,
    kChipSoundFile_CHIO_DOG_EMO_RESPONSE_2A=137,
    kChipSoundFile_SHORT_MUTE_FOR_STOP=138,

};

typedef NS_OPTIONS(uint8_t, kChipBodyconType) {
    kChipBodyconReset = 0x01,
    kChipBodyconSit = 0x02,
    kChipBodyconLieDown = 0x03,
    kChipBodyconAllIdleMode = 0x04,
    kChipBodyconDance = 0x05,
    kChipBodyconVRTraining1 = 0x06,
    kChipBodyconVRTraining2 = 0x07,
    kChipBodyconReset2 = 0x08,
    kChipBodyconJump = 0x09,
    kChipBodyconYoga = 0x0a,
    kChipBodyconWatchCome = 0x0b,
    kChipBodyconWatchFollow = 0x0c,
    kChipBodyconWatchFetch = 0x0d,
    kChipBodyconBallTracking = 0x0e,
    kChipBodyconBallSoccer = 0x0f,
    kChipBodyconBase = 0x10,
    kChipBodyconDanceBase = 0x11,
    kChipBodyconStopOrStandFromBase = 0x12,
    kChipBodyconGuardMode = 0x13,
    kChipBodyconFreeRoam = 0x14,
    kChipBodyconFaceDownForControllingChippies = 0x15,
};

//0x46
typedef NS_OPTIONS(uint8_t, kChipSpeed) {
    kChipAdultSpeed = 0x00,
    kChipKidSpeed = 0x01
};


typedef NS_OPTIONS(uint8_t, kChipChargerType) {
    kChipChargerTypeDC = 0x00,
    kChipChargerTypeBase = 0x01,    //charging bed
};

@interface ChipCommandValues : NSObject

@end

